env:
  env_name: PegInsertionRandomizedMarkerEnv-v1
  # env parameters
  step_penalty: 1
  final_reward: 10
  max_action_mm_deg: [2.0, 2.0, 4.0]
  max_steps: 8
  normalize: False
  z_step_size_mm: 0.125
  peg_hole_path_file: "configs/peg_insertion/3shape_1.5mm.txt"
  peg_theta_max_offset_deg: 10.0
  peg_x_max_offset_mm: 5.0
  peg_y_max_offset_mm: 5.0
  gui: False

  # marker parameters
  render_rgb: True
  marker_interval_range: [1.95, 2.15]
  marker_lose_tracking_probability: 0.01
  marker_pos_shift_range: [0.1, 0.1]
  marker_random_noise: 0.5
  marker_rotation_range: 0.1
  marker_translation_range: [1, 1]
  

  params:
    # simulation parameters
    sim_time_step: 0.1
    sim_d_hat: 0.0001
    sim_eps_d: 0
    sim_eps_v: 0.01
    sim_kappa: 100.0
    sim_kappa_affine: 100000.0
    sim_kappa_con: 10000000000.0
    # simulation solver parameters
    sim_solver_newton_max_iters: 5
    sim_solver_cg_max_iters: 50
    sim_solver_cg_error_frequency: 10
    sim_solver_cg_error_tolerance: 0
    # tactile sensor parameters
    tac_sensor_meta_file: gelsight_mini_e430/meta_file
    tac_density_l: 1000.0
    tac_density_r: 1000.0
    tac_elastic_modulus_l: [300000.0, 300000.0]
    tac_elastic_modulus_r: [300000.0, 300000.0]
    tac_friction: [50.0, 125.0]
    tac_poisson_ratio_l: [ 0.3, 0.3 ]
    tac_poisson_ratio_r: [ 0.3, 0.3 ]
    allow_self_collision: False
    ccd_max_iters: 100
    ccd_slackness: 0.7
    ccd_thickness: 1e-6
    ccd_tet_inversion_thres: 0.0
    ee_classify_thres: 0.001
    ee_mollifier_thres: 0.001
    line_search_max_iters: 10
    # task specific parameters
    gripper_x_offset_mm: [ -1, 1 ]
    gripper_z_offset_mm: [ -10, -6 ]
    indentation_depth_mm: [ 0.5, 1.25 ]
    peg_friction: [ 4.0, 15.0 ]
    hole_friction: [ 0.0, 1.0 ]


policy:
  policy_name: TD3PolicyForPointFlowEnv
  buffer_size: 10000
  train_freq: 2
  gradient_steps: -1
  learning_starts: 1000
  target_policy_noise: 0.5
  target_noise_clip: 1
  action_noise: 0.5
  batch_size: 128
  learning_rate: 0.0003
  policy_delay: 5

  policy_kwargs:
    net_arch:
      pi: [256, 256]
      qf: [256, 256]
    pointnet_in_dim: 4
    pointnet_out_dim: 32
    pointnet_batchnorm: False
    pointnet_layernorm: True
    zero_init_output: True
    use_relative_motion: True

train:
  algorithm_name: TD3
  total_timesteps: 400000
  log_interval: 10
  checkpoint_every: 2000
  eval_freq: 2000
  n_eval: 50
  parallel: 24
  # parallel: An integer or a list of integers.
  # If you have just one GPU, we recommend using an integer.
  # If an integer is used, it represents the number of TRAIN environments you want to run in parallel,
  # and the GPU used by the environment is automatically selected.
  # If an integer list is used, the environment will be built on the specified GPU, including both TRAIN and EVAL environments.
  # In this case, the last number in the list specifies the GPU for the EVAL environment.
  seed: 0
  device: "cuda"
  gpu: 0
  name: "3shape_1.5mm"
  
